Gemfile, Gemfile.lock, config/database.yml
=> change_detabase

Gemfile, Gemfile.lock, config/unicorn.rb
ユニコーンのインストール
本番環境でrailsを起動するため
=> Autodeploy preparation

app/assets/images/google.svg, app/assets/stylesheets/yukawa.scss, app/controllers/yukawa_controller.rb, app/views/yukawa/index.html.haml, config/routes.rb
WHAT
新規登録画面のビュー
WHY
のちのち朝倉さんの作ったヘッダーとフッターをrenderします。
=> resistration View

app/assets/stylesheets/mypage_nav.scss, app/views/shared/_items_html.haml, app/views/shared/_mypage_nav.html.haml
イメージタグの矢印をアイコンに変更
items sectionを共通部品化
チームの効率改善の為
=> Icon modify in nav bar

app/controllers/application_controller.rb, config/deploy.rb, config/deploy/production.rb
basic認証を本番環境でのみ実装
本家のメルカリユーザーに誤解を与えない為
=> [WIP]Basic authentication

app/controllers/application_controller.rb
basic認証の無効化
ビューが本番環境で表示されているかだけをまず確かめる為
=> basic認証の無効化

app/controllers/application_controller.rb, config/deploy.rb
deploy.rbの記述をBASIC_AUTH_USERからusernameに変更しました
basic認証を本番環境で行う為
=> deploy.rb内の環境変数を修正

app/views/signup/address.html.haml, app/views/signup/how_pay.html.haml, app/views/signup/index.html.haml, app/views/signup/login.html.haml, app/views/signup/registration.html.haml, app/views/signup/sms_confirmation.html.haml, app/views/yukawa/clear_compleate.html.haml
=> 新規登録画面のfooter

app/assets/stylesheets/buy_comfirmation.scss
=> 購入確認画面のSCSSファイル修正

app/assets/stylesheets/inagawa/item_detail.scss, app/assets/stylesheets/shared/_item.scss, app/views/inagawa/show.html.haml
商品詳細ページのリファクタリング
変更に強く、見やすいコードにするため
=> Modify items show

app/models/address.rb, app/models/user.rb, config/initializers/devise.rb, config/locales/devise.en.yml, config/routes.rb, db/migrate/20190727030054_devise_create_users.rb, db/migrate/20190727032545_create_addresses.rb, db/schema.rb, test/fixtures/addresses.yml, test/fixtures/users.yml, test/models/address_test.rb, test/models/user_test.rb
=> db devise Update

app/assets/javascripts/comments.coffee, app/assets/stylesheets/comments.scss, app/controllers/comments_controller.rb, app/controllers/items_controller.rb, app/helpers/comments_helper.rb, app/models/comment.rb, app/models/item.rb, app/models/user.rb, app/views/items/show.html.haml, app/views/shared/_item.html.haml, config/routes.rb, db/migrate/20190728055205_create_comments.rb, db/schema.rb, test/controllers/comments_controller_test.rb, test/fixtures/comments.yml, test/models/comment_test.rb
=> Comments function

app/controllers/signup_controller.rb, app/models/user.rb
=> supel miss

app/uploaders/image_uploader.rb, app/views/items/show.html.haml, config/deploy.rb, config/initializers/carrierwave.rb
画像の保存先をS３へ変更
ストレージサービスを利用することで容量の圧迫を防ぐため
=> S3 install

app/controllers/items_controller.rb, app/uploaders/image_uploader.rb, app/views/items/new.html.haml
環境ごとの画像保存先の設定
自分以外のメンバーのローカル環境での画像の保存を可能にするため
=> 環境ごとの保存先の設定

app/controllers/items_controller.rb, app/views/items/show.html.haml, config/initializers/carrierwave.rb
=> Show page's photo error

spec/factories/items.rb, spec/models/item_spec.rb
=> itemのfactory bot作成

spec/factories/images.rb, spec/factories/items.rb, spec/factories/users.rb, spec/models/image_spec.rb, spec/models/item_spec.rb, spec/models/user_spec.rb, spec/rails_helper.rb
＃ what
modelのテストコーディング
validationや仕様漏れがないかを確認するため
=> Items test codings

app/models/user.rb, spec/factories/address.rb, spec/factories/users.rb, spec/models/address_spec.rb, spec/models/image_spec.rb, spec/models/item_spec.rb, spec/models/user_spec.rb
user model, address modelのテストをRSpecを使用し、実施
仕様漏れや、バリデーションの有無を確認する為
=> [WIP]User address test codings

Gemfile, Gemfile.lock, app/controllers/items_controller.rb, app/views/items/show.html.haml, spec/controllers/items_controller_spec.rb, spec/factories/items.rb
items controllerのテストコーディング
それぞれのページへの遷移、インスタンス変数が予想する値になっているかなどを確認する為
=> Items controller test

app/assets/javascripts/selling_item_images.js, app/assets/stylesheets/asakura.scss, app/views/items/new.html.haml
What
商品出品の際に、画像のプレビューの表示する機能を実装しました。
ドラッグアンドドロップの機能はまだ実装できていません。
Why
出品機能の機能向上のため
https://gyazo.com/d70187860dd30d04656b3dfd87ff27f9
=> 商品出品画面のプレビューと保存

app/assets/javascripts/sell-item-validation.js, app/assets/stylesheets/asakura.scss, app/views/items/new.html.haml
What
エラーメッセージを出力させるためにsell-item-validation.jsを作成・編集
Why
バリデーションの確認も兼ねて
=> 出品画面バリデーションのエラーメッセージ

app/assets/javascripts/price.js, app/assets/stylesheets/asakura.scss, app/views/items/new.html.haml
What
jsを使い、価格を打ち込むと10％の手数料と価格から手数料を引いた販売利益を表示させる。
=> 販売手数料と販売利益の表示

app/controllers/items_controller.rb, db/schema.rb
本番環境でも画像の編集ができるようにするためにeditアクションを編集しました。
=> 本番環境での画像の編集

app/assets/stylesheets/jinno.scss, app/controllers/transaction_controller.rb, app/views/items/index.html.haml
=> Buy controller

app/assets/stylesheets/inagawa/item_detail.scss, app/views/items/show.html.haml
What
商品詳細ページのカテゴリーを表示させる
リンク先は仮でルートパスに設定
Why
微調整のため
=> 商品詳細のカテゴリー表示

app/controllers/items_controller.rb
=> except Category

app/assets/javascripts/modal.js, app/assets/stylesheets/inagawa/item_detail.scss, app/views/items/index.html.haml, app/views/items/search.html.haml, app/views/items/show.html.haml, app/views/shared/_item.html.haml, config/breadcrumbs.rb
商品削除時にモーダルウインドウで削除確認をする機能を実装
ユーザーが間違えて削除ボタンを押してしまうことがあるため
=> [WIP]Delete modal

app/controllers/mypages_controller.rb, app/views/mypages/listing_list.html.haml
What
出品した商品一覧をマイページに表示させる
Why
新規会員登録ができず他のユーザーで購入できないので、第一段階としてマージさせます
=> マイページに出品商品一覧の表示

app/views/mypages/listing_list.html.haml, app/views/transaction/index.html.haml
What
マイページの出品一覧画面に商品を表示
購入された商品は出品一覧に出ないようにする
=> マイページで出品商品一覧表示

app/assets/stylesheets/users/mypages.scss, app/controllers/mypages_controller.rb, app/views/mypages/listing_completed.html.haml, app/views/mypages/listing_list.html.haml, app/views/mypages/show.html.haml, app/views/shared/_mypage_nav.html.haml, config/routes.rb
What
ユーザーが出品した商品をマイページに表示させる
→他のユーザーが購入前の商品は「出品した商品 - 出品中」を一覧で表示させる
→他のユーザーが購入した商品は「出品した商品 - 売却済み」で一覧を表示させる
Why
出品した商品の状況把握をしやすくするため
=> マイページに出品した商品を表示させる

app/assets/stylesheets/users/mypages.scss, app/controllers/mypages_controller.rb, app/models/item.rb, app/models/transaction.rb, app/models/user.rb, app/views/mypages/purchased.html.haml, app/views/mypages/show.html.haml, app/views/shared/_mypage_nav.html.haml, config/routes.rb
What
・「購入した商品 - 過去の取引」に一覧を表示させる
・マイページのトップ画面下部にも同様に購入商品を一覧で表示させる
Why
商品の取引状況を分かりやすくするため
=> マイページに購入商品の一覧を表示させる

app/assets/stylesheets/items/items.scss, app/models/item.rb
=> 商品削除時に付随するコメントも削除

app/assets/stylesheets/users/mypages.scss, app/views/mypages/listing_completed.html.haml, app/views/mypages/listing_list.html.haml, app/views/mypages/purchased.html.haml, app/views/mypages/show.html.haml, app/views/shared/_mypage_nav.html.haml
What
出品中/売却済/購入済の商品の有無によってそれぞれビューを変える
レイアウトの微調整
Why
見やすくするため
=> マイページのビュー調整

app/views/items/show.html.haml
コメントに対する画像表示をimage tagに差し替え
本番環境でも画像を表示させる為
=> image tagへ差し替え
